version: "3"
services:
  mssql:
    container_name: dev-mssql
    hostname: mssql
    image: "mcr.microsoft.com/mssql/server"
    environment:
        # Username: sa
        SA_PASSWORD: "reallyStrongPwd123"
        ACCEPT_EULA: "Y"
    ports:
        - '1433:1433'
    deploy:
        resources:
            limits:
                memory: 2048M
